brew "fastfetch"
brew "ffmpeg"
brew "gh"
brew "git"
brew "mas"
brew "p7zip"
brew "wget"
cask "adguard"
cask "adguard-vpn"
cask "alt-tab"
cask "anki"
cask "appcleaner"
cask "brave-browser"
cask "cursor"
cask "discord"
cask "drawio"
cask "firefox"
cask "font-inconsolata"
cask "font-myrica"
cask "font-myricam"
cask "google-chrome"
cask "google-japanese-ime"
cask "jdownloader"
cask "karabiner-elements"
cask "logi-options+"
cask "macwinzipper"
cask "microsoft-edge"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "notion"
cask "obsidian"
cask "proton-pass"
cask "raindropio"
cask "raycast"
cask "tor-browser"
cask "utm"
cask "visual-studio-code"
cask "vlc"
cask "warp"
mas "MenubarX", id: 1575588022
mas "RunCat", id: 1429033973
mas "Telegram", id: 747648890
mas "The Unarchiver", id: 425424353
